- name: Install MariaDB Docker image
  hosts: mariadbhosts
  become: true
  vars:
    docker_network: custom_network
    mariadb_version: 11.4
  tasks:
    - name: include vault
      ansible.builtin.include_vars:
        file: group_vars/mariadbhosts/vault.yml

    - name: Create a network if it doesn't exist
      community.docker.docker_network:
        name: "{{ docker_network }}"
        state: present

    - name: Ensure MariaDB container is running
      community.docker.docker_container:
        name: mariadb_container
        image: mariadb:{{mariadb_version}}
        state: present
        recreate: true
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: "{{ mariadb_root_password }}"
        volumes:
          - /var/lib/mysql:/var/lib/mysql
        restart_policy: always
        networks:
          - name: "{{ docker_network }}"

    - name: Install MySQL client
      ansible.builtin.apt:
        name: default-mysql-client
        state: present
        update_cache: true
